version: '3.7'

services:

    client:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        environment:
            CHOKIDAR_USEPOLLING: "true"
        tty: true
        ports:
            - "3000:3000"
        volumes: 
            - ./frontend:/app
            - /app/node_modules
        networks:
            - frontend

    api:
        build: 
            context: ./backend
            dockerfile: Dockerfile
        ports:
            - "5000:5000"
        volumes:
            - ./backend:/app
        environment: 
            FLASK_ENV: development
        networks:
            - frontend
            - backend

networks:
    frontend:
        driver: bridge
    backend:
        driver: bridge
volumes:
    appdata:
        driver: local